#define ID 0
#define CONST 1
#define HASH 2
#define INCLUDE 3
#define TWICE_LESS_THAN 4
#define LESS_THAN 5
#define IOSTREAM 6
#define TWICE_MORE_THAN 7
#define MORE_THAN 8
#define USING 9
#define NAMESPACE 10
#define STD 11
#define SEMICOLON 12
#define INT 13
#define FLOAT 14
#define MAIN 15
#define LEFT_PARANTHESIS 16
#define RIGHT_PARANTHESIS 17
#define LEFT_BRACE 18
#define EQUAL 19
#define RIGHT_BRACE 20
#define RETURN 21
#define STRUCT 22
#define IF 23
#define WHILE 24
#define CIN 25
#define COUT 26
#define ELSE 27
#define LESS_THAN_OR_EQUAL 28
#define MORE_THAN_OR_EQUAL 29
#define TWICE_EQUAL 30
#define DIFFERENT 31
#define COMMA 32
#define PLUS 33
#define MINUS 34
#define ASTERISK 35
#define SLASH 36
#define PERCENT 37
#define DOT 38