IDENTIFIERS_FA_FILENAME = 'data\\input\\identifiers_finite_automata.txt'
INTEGER_CONSTANTS_FA_FILENAME = 'data\\input\\integers_finite_automata.txt'
INTERNAL_FORM_FILENAME = 'data\\output\\internal form.txt'
REAL_CONSTANTS_FA_FILENAME = 'data\\input\\reals_finite_automata.txt'
SOURCE_CODE_FILENAME = 'example.cpp'
SYMBOLS_TABLE_FILENAME = 'data\\output\\symbols table.txt'
TOKENS_FILENAME = 'data\\input\\tokens.txt'
